apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pytorch-checkpoints
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: dgx-nfs  # multi-node needs RWX
  resources:
    requests:
      storage: 1Ti
